### ISSUE TITLE
Apon relogging title.sh and info.sh use 100% cpu

### ISSUE THREAD

**Issue by lordzweigar** [neeasade/dotfiles#4]
when using lightdm (yes, this again) apon relogging more instances of title.sh and info.sh are spawned
either a function that will only let one instance run or a log out script are needed.
Thanks for the rice.

**Comment by lordzweigar** [comment]
appeding this:  if [ `ps -e | grep -c $(info.sh $0)` -gt 2 ]; then exit 0; fi
helps a bit (a pgrep ensures that only one instance is running) but the script it's self is still a bit power hungry.
EDIT: however this doesn't work across reloads of x.

**Comment by neeasade** [comment]
Hi, had a fix for this a few days ago but hadn't pushed because it wasn't a big change - sorry about that. I'm making the assumption that you are killing the session with the keybind in the sxhkd - which was not killing the panel previously. Pushed up in lasted commit, see https://github.com/neeasade/dotfiles/blob/master/home/sxhkd/.config/sxhkd/sxhkdrc#L114

since info.sh is under the panel script, it should be killed as well with that.

**Comment by neeasade** [comment]
I do realize that the above doesn't affect the scripts power hungry-ness, though. You can reduce this by increasing the interval used to refresh the info.sh information or by using fewer bar options. 

Edit: I'm psyched you're using my dots, m8

**Comment by lordzweigar** [comment]
ty
